name: movies
description: Movies
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.9
  flutter_sticky_header: ^0.4.2
  get_it: ^4.0.0
  injectable: ^0.2.3
  json_annotation: ^3.0.1
  pretty_dio_logger: ^1.1.0
  provider: ^4.0.4
  retrofit: ^1.3.1+1
  shared_preferences: ^0.5.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.4
  injectable_generator: ^0.2.3
  json_serializable: ^3.2.5
  mockito: ^4.1.1
  retrofit_generator: ^1.3.1+3

flutter:
  uses-material-design: true

  assets:
    - assets/images/poster-placeholder.png
