name: movies
description: Movies
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.8
  get_it: ^3.1.0
  injectable: ^0.2.2
  json_annotation: ^3.0.1
  provider: ^4.0.4
  retrofit: ^1.3.0
  shared_preferences: ^0.5.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.4
  injectable_generator: ^0.2.2
  json_serializable: ^3.2.5
  retrofit_generator: ^1.3.0

flutter:
  uses-material-design: true
